controller:
  image: "jenkins/jenkins"
  tag: "2.283-jdk11"
  overwritePlugins: true
  initScripts:
    - |
      import jenkins.model.Jenkins
  installPlugins:
    - "ace-editor:1.1"
    - "all-changes:1.5"
    - "ansicolor:0.7.5"
    - "apache-httpcomponents-client-4-api:4.5.13-1.0"
    - "authentication-tokens:1.4"
    - "bootstrap4-api:4.6.0-2"
    - "bouncycastle-api:2.20"
    - "branch-api:2.6.3"
    - "checks-api:1.6.0"
    - "cloudbees-bitbucket-branch-source:2.9.7"
    - "cloudbees-folder:6.15"
    - "command-launcher:1.5"
    - "configuration-as-code:1.47"
    - "credentials:2.3.15"
    - "credentials-binding:1.24"
    - "dashboard-view:2.14"
    - "display-url-api:2.3.4"
    - "durable-task:1.35"
    - "echarts-api:5.0.1-1"
    - "font-awesome-api:5.15.2-2"
    - "git:4.6.0"
    - "git-client:3.6.0"
    - "git-server:1.9"
    - "google-kubernetes-engine:0.8.4"
    - "google-oauth-plugin:1.0.3"
    - "handlebars:1.1.1"
    - "handy-uri-templates-2-api:2.1.8-1.0"
    - "jackson2-api:2.12.1"
    - "jaxb:2.3.0.1"
    - "jdk-tool:1.5"
    - "jquery3-api:3.5.1-3"
    - "jsch:0.1.55.2"
    - "junit:1.48"
    - "kubernetes:1.29.2"
    - "kubernetes-client-api:4.13.2-1"
    - "kubernetes-credentials:0.8.0"
    - "lockable-resources:2.10"
    - "mailer:1.32.1"
    - "matrix-auth:2.6.5"
    - "matrix-project:1.18"
    - "metrics:4.0.2.7"
    - "modernstatus:1.3"
    - "momentjs:1.1.1"
    - "oauth-credentials:0.4"
    - "pipeline-build-step:2.13"
    - "pipeline-graph-analysis:1.10"
    - "pipeline-input-step:2.12"
    - "pipeline-milestone-step:1.3.2"
    - "pipeline-model-api:1.8.4"
    - "pipeline-model-definition:1.8.4"
    - "pipeline-model-extensions:1.8.4"
    - "pipeline-rest-api:2.19"
    - "pipeline-stage-step:2.5"
    - "pipeline-stage-tags-metadata:1.8.4"
    - "pipeline-stage-view:2.19"
    - "plain-credentials:1.7"
    - "plugin-util-api:2.0.0"
    - "popper-api:1.16.1-2"
    - "resource-disposer:0.15"
    - "role-strategy:3.1"
    - "scm-api:2.6.4"
    - "script-security:1.76"
    - "simple-theme-plugin:0.6"
    - "snakeyaml-api:1.27.0"
    - "ssh-credentials:1.18.1"
    - "sshd:3.0.3"
    - "structs:1.22"
    - "timestamper:1.11.8"
    - "trilead-api:1.0.13"
    - "variant:1.4"
    - "workflow-aggregator:2.6"
    - "workflow-api:2.41"
    - "workflow-basic-steps:2.23"
    - "workflow-cps:2.90"
    - "workflow-cps-global-lib:2.18"
    - "workflow-durable-task-step:2.38"
    - "workflow-job:2.40"
    - "workflow-multibranch:2.22"
    - "workflow-scm-step:2.12"
    - "workflow-step-api:2.23"
    - "workflow-support:3.8"
    - "ws-cleanup:0.39"
  resources:
    requests:
      cpu: "1"
      memory: "4096Mi"
    limits:
      cpu: "3"
      memory: "4096Mi"
  containerEnv:
    - name: TZ
      value: "America/Santiago"
  javaOpts: "-Xms256m -Xmx4096m -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.defaultImage=jenkins/inbound-agent:4.6-1-jdk11"
  serviceType: "NodePort"
  jenkinsUrl: "https://jenkins.tu-dominio.com"
  ingress:
    enabled: false
  JCasC:
    enabled: true
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "${chart-admin-username}"
          name: "jenkins-admin"
          password: "${chart-admin-password}"
    authorizationStrategy: |-
      roleBased:
           roles:
             global:
             - assignments:
               - "admin"
               name: "admin"
               pattern: ".*"
               permissions:
               - "Job/Move"
               - "Job/Build"
               - "Lockable Resources/View"
               - "Credentials/Delete"
               - "Credentials/ManageDomains"
               - "Lockable Resources/Unlock"
               - "View/Create"
               - "Agent/Configure"
               - "Job/Read"
               - "Credentials/Update"
               - "Agent/Create"
               - "Job/Delete"
               - "Agent/Build"
               - "View/Configure"
               - "Metrics/HealthCheck"
               - "Lockable Resources/Reserve"
               - "Agent/Provision"
               - "Metrics/ThreadDump"
               - "SCM/Tag"
               - "Job/Create"
               - "Job/Discover"
               - "Credentials/View"
               - "Agent/Connect"
               - "Agent/Delete"
               - "Run/Replay"
               - "Agent/Disconnect"
               - "Run/Delete"
               - "Job/Cancel"
               - "Overall/Read"
               - "Run/Update"
               - "Credentials/Create"
               - "Overall/Administer"
               - "View/Delete"
               - "Job/Configure"
               - "Metrics/View"
               - "Job/Workspace"
               - "View/Read"
    configScripts:
      config-jcasc: |
        jenkins:
          agentProtocols:
          - "JNLP4-connect"
          - "Ping"
          disabledAdministrativeMonitors:
          - "jenkins.security.QueueItemAuthenticatorMonitor"
          globalNodeProperties:
          - envVars:
              env:
              - key: "CORPORATION"
                value: "acme corp"
              - key: "GCP_LOCATION"
                value: "google-region"
          labelAtoms:
          - name: "jenkins-agent"
          - name: "master"
          primaryView:
            all:
              name: "all"
          quietPeriod: 5
          scmCheckoutRetryCount: 0
          slaveAgentPort: 50000
          updateCenter:
            sites:
            - id: "default"
              url: "https://updates.jenkins.io/update-center.json"
          views:
          - all:
              name: "all"
          viewsTabBar: "standard"
        security:
          sSHD:
            port: -1
        unclassified:
          ansiColorBuildWrapper:
            colorMaps:
            - black: "#000000"
              blackB: "#4C4C4C"
              blue: "#1E90FF"
              blueB: "#4682B4"
              cyan: "#00CDCD"
              cyanB: "#00FFFF"
              green: "#00CD00"
              greenB: "#00FF00"
              magenta: "#CD00CD"
              magentaB: "#FF00FF"
              name: "xterm"
              red: "#CD0000"
              redB: "#FF0000"
              white: "#E5E5E5"
              whiteB: "#FFFFFF"
              yellow: "#CDCD00"
              yellowB: "#FFFF00"
            - black: "#000000"
              blackB: "#555555"
              blue: "#0000AA"
              blueB: "#5555FF"
              cyan: "#00AAAA"
              cyanB: "#55FFFF"
              defaultBackground: 0
              defaultForeground: 7
              green: "#00AA00"
              greenB: "#55FF55"
              magenta: "#AA00AA"
              magentaB: "#FF55FF"
              name: "vga"
              red: "#AA0000"
              redB: "#FF5555"
              white: "#AAAAAA"
              whiteB: "#FFFFFF"
              yellow: "#AA5500"
              yellowB: "#FFFF55"
            - black: "black"
              blackB: "black"
              blue: "blue"
              blueB: "blue"
              cyan: "cyan"
              cyanB: "cyan"
              green: "green"
              greenB: "green"
              magenta: "magenta"
              magentaB: "magenta"
              name: "css"
              red: "red"
              redB: "red"
              white: "white"
              whiteB: "white"
              yellow: "yellow"
              yellowB: "yellow"
            - black: "#2E3436"
              blackB: "#2E3436"
              blue: "#3465A4"
              blueB: "#3465A4"
              cyan: "#06989A"
              cyanB: "#06989A"
              defaultBackground: 0
              defaultForeground: 7
              green: "#4E9A06"
              greenB: "#4E9A06"
              magenta: "#75507B"
              magentaB: "#75507B"
              name: "gnome-terminal"
              red: "#CC0000"
              redB: "#CC0000"
              white: "#D3D7CF"
              whiteB: "#D3D7CF"
              yellow: "#C4A000"
              yellowB: "#C4A000"
            globalColorMapName: "xterm"
          bitbucketEndpointConfiguration:
            endpoints:
            - bitbucketCloudEndpoint:
                enableCache: false
                manageHooks: false
                repositoriesCacheDuration: 180
                teamCacheDuration: 360
          buildDiscarders:
            configuredBuildDiscarders:
            - "jobBuildDiscarder"
          fingerprints:
            fingerprintCleanupDisabled: false
            storage: "file"
          gitSCM:
            addGitTagAction: false
            allowSecondFetch: true
            createAccountBasedOnEmail: false
            disableGitToolChooser: true
            hideCredentials: true
            showEntireCommitSummaryInChanges: false
            useExistingAccountWithSameEmail: false
          globalDefaultFlowDurabilityLevel:
            durabilityHint: PERFORMANCE_OPTIMIZED
          junitTestResultStorage:
            storage: "file"
          mailer:
            charset: "UTF-8"
            useSsl: false
            useTls: false
          pollSCM:
            pollingThreadCount: 10
          simple-theme-plugin:
            elements:
            - cssUrl:
                url: "https://8ab972673b5689e842a8-4ce0e842e9a020b19bb3a8bec8532674.ssl.cf1.rackcdn.com/canon-jenkins/style.css"
          timestamper:
            allPipelines: true
            elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
            systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
        tool:
          git:
            installations:
            - home: "git"
              name: "git"
          mavenGlobalConfig:
            globalSettingsProvider: "standard"
            settingsProvider: "standard"
agent:
  enabled: false
persistence:
  existingClaim: "pvc-fileserver-jenkins"
serviceAccount:
  name: "jenkins-sa"
